### ISSUE TITLE
Internet good for this

### ISSUE THREAD

**Issue by DeLuca92** [phreakyphoenix/WhastAppBulkMessager#4]
I thinking rent a vps for use this service.
I have 100 mb, but for send 1 msg the time is 11 segs.
I dont know if is the internet or a pc.
But I know if I have a good internet is send faster than now

**Comment by phreakyphoenix** [comment]
Yes, a good internet connectivity is required, on both your desktop and your mobile, for it to work well.
It should take at most four seconds per message, but the code won't fail even if it takes longer and your message will be delivered.
If your issue is resolved, please consider closing the issue.

**Comment by phreakyphoenix** [comment]
Closing it due to inactivity. Hope your issue is resolved.

**Comment by kushnagda** [comment]
Hi, can you help me with the chrome driver?
I have installed it and tried to run the code but it was throwing error on line 25 

DevTools listening on ws://127.0.0.1:50901/devtools/browser/ec122033-ebf8-4855-8286-5e04af2602d8
Traceback (most recent call last):
  File "run.py", line 25, in <module>

my version of chrome is Version 83.0.4103.116 (Official Build) (64-bit)

let me know what can be done 

Thank you In advance

**Comment by phreakyphoenix** [comment]
I'm not really sure about the ws: url. My guess is you're using chrome devtools, but that has nothing to do with this program. 

Line 25 starts the webdriver, an error on which would indicate an improper installation of chrome webdriver. Instructions for this will be available online. Plz note devtools is not required, in case you're using it. Trying to open the google search page using some basic tutorial should sort out this problem.

Additionally, I'd appreciate a different issue for further queries, as this issue is about internet speed and yours is not connected to it.
