### ISSUE TITLE
(video) Not send the message

### ISSUE THREAD

**Issue by DevDorrejo** [phreakyphoenix/WhastAppBulkMessager#6]
the program do like work, but when open whatsapp web, after that do nothing and not send the message.
https://www.youtube.com/watch?v=Eik8DxB5OX8&feature=youtu.be

**Comment by phreakyphoenix** [comment]
I'm sorry for the late reply, it must have been due to the css_selector in the program, below the comment "Update css selector if u have any issues". How to find the css selector is already mentioned in the Readme too.  
Also, try pulling the updated code from this repo. And feel free to reopen if the issue persists.
